import {
  Building2,
  Database,
  FileSpreadsheet,
  LockKeyhole,
  Printer,
  Settings2,
  SlidersHorizontal,
} from "lucide-react";
import { Header } from "@/components/dashboard/Header";
import { Sidebar } from "@/components/dashboard/Sidebar";

const settingSections = [
  {
    icon: Building2,
    title: "Company Profile",
    description: "Keep the business identity used across invoices and reports in one place.",
    items: [
      "Business name, address, phone, email, website",
      "Logo and favicon used on reports and printed invoices",
      "Default invoice footer note and signature block",
    ],
  },
  {
    icon: Printer,
    title: "Invoice and Print Settings",
    description: "Control how printed invoices and A4 reports should look and behave.",
    items: [
      "Invoice title, paper size, and print layout defaults",
      "Show or hide payment history, notes, or footer sections",
      "Default filename format for Save as PDF",
    ],
  },
  {
    icon: FileSpreadsheet,
    title: "Report Defaults",
    description: "Set how dashboard and sales reports should be generated by default.",
    items: [
      "Preferred report range: week, month, year, or custom",
      "What metrics to show on A4 summary reports",
      "Table row limits for top customers, items, and invoices",
    ],
  },
  {
    icon: SlidersHorizontal,
    title: "System Preferences",
    description: "Technical behavior of the app that affects how users see and operate the system.",
    items: [
      "Dark / light theme preference",
      "Default pagination size for long tables",
      "Default dashboard date range such as week, month, or year",
      "Timezone selection for dates, reports, and transaction defaults",
    ],
  },
  {
    icon: LockKeyhole,
    title: "Access and Admin",
    description: "Keep login and permissions clear as the system grows beyond one admin.",
    items: [
      "Admin profile details and password reset flow",
      "Add staff roles later if multiple users access the app",
      "Restrict sensitive actions like delete or report export",
    ],
  },
  {
    icon: Database,
    title: "Data and System Setup",
    description: "Operational settings tied to Supabase and day-to-day bookkeeping structure.",
    items: [
      "Backup and export strategy for sales, purchases, suppliers, and staff",
      "Default numbering rules for invoices, purchases, suppliers, and staff codes",
      "Future toggles for tax, payment methods, and product catalog behavior",
    ],
  },
];

export default function SettingsPage() {
  return (
    <div className="flex min-h-screen bg-slate-50/50">
      <Sidebar />

      <main className="flex-1 overflow-y-auto p-8">
        <Header
          title="Settings"
          description="Operational controls for company identity, print outputs, reports, access, and system defaults."
        />

        <div className="mb-8 rounded-[28px] border border-slate-200 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-6 text-white shadow-sm">
          <div className="flex items-start gap-4">
            <div className="rounded-2xl bg-white/10 p-3 text-slate-100">
              <Settings2 className="h-6 w-6" />
            </div>
            <div>
              <h3 className="text-xl font-bold">What should live in Settings</h3>
              <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">
                This page is now clickable and acts as the home for business-wide preferences.
                The sections below are the right places to centralize invoice branding, report
                defaults, numbering rules, auth controls, and future system behavior.
              </p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
          {settingSections.map((section) => (
            <section
              key={section.title}
              className="rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"
            >
              <div className="flex items-start gap-4">
                <div className="rounded-2xl bg-slate-50 p-3 text-slate-700">
                  <section.icon className="h-5 w-5" />
                </div>
                <div className="min-w-0">
                  <div className="text-[11px] font-bold uppercase tracking-[0.24em] text-slate-400">
                    Settings Area
                  </div>
                  <h3 className="mt-2 text-lg font-bold text-slate-900">{section.title}</h3>
                  <p className="mt-2 text-sm leading-6 text-slate-500">{section.description}</p>
                </div>
              </div>

              <div className="mt-5 space-y-3">
                {section.items.map((item) => (
                  <div
                    key={item}
                    className="rounded-2xl border border-slate-100 bg-slate-50/70 px-4 py-3 text-sm text-slate-700"
                  >
                    {item}
                  </div>
                ))}
              </div>
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
